---
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.x

require:
  - rubocop-rake
  - rubocop-rspec

Style/NegatedIf:
  Enabled: false

Metrics/MethodLength:
  CountAsOne:
    - 'array'
    - 'hash'
    - 'heredoc'
  Max: 25

Metrics/BlockLength:
  CountAsOne:
    - 'array'
    - 'hash'
    - 'heredoc'

Style/Documentation:
  Enabled: false
